### ISSUE TITLE
OSX GUI hangs at 'Welcome to DriveShare' screen

### ISSUE THREAD

**Issue by Kryptokat** [Storj/driveshare-gui#103]
Picked this up doing a first install on osx 10.9.4.
![screen shot 2015-12-12 at 4 03 31 pm](https://cloud.githubusercontent.com/assets/8479163/11763009/16772022-a102-11e5-98ac-be22fb718003.png)

**Comment by bierlingm** [comment]
I have the exact same issue.

**Comment by super3** [comment]
@Kryptokat @bierlingm We will investigate this Monday.

**Comment by littleskunk** [comment]
Dataserv-client download failed. Thats the reason for this bug. File name of the dataserv-client is hardcoded. The old name was dataserv-client-2.1.4.osx32.zip but that name was wrong. It was a 64bit binary. The new release is dataserv-client-2.1.12.osx64.zip.

I see 2 bugs here. 
1.) I would expect a error message like driveshare-gui 0.3.4 did.
2.) I can live with a hardcoded 64bit file name.

Workaround will follow. Give me some minutes to build a new binary with a little hotfix.

**Comment by gordonwritescode** [comment]
Actual fix will be to use the GitHub releases API, I'll work on it next week.

**Comment by gordonwritescode** [comment]
(In addition to better error handling)

**Comment by littleskunk** [comment]
Retest with hotfix passed. You can download it here:
https://github.com/Storj/driveshare-gui/releases/download/0.4.1/DriveShare_0.4.1.osx64.hotfix.dmg

I merge everything into develop branch. That way @gordonwritescode has more time for his final solution / we can release 0.4.2 any time if needed.

**Comment by gordonwritescode** [comment]
I'm sorry, I misspoke, we are using the Releases API. Your hotfix is good for the foreseeable future (unless we later decide to build osx32 and osx64 binaries, but I can't imagine why we would). Closing!

**Comment by gordonwritescode** [comment]
Oh, but reopening to add proper error messaging!

**Comment by gordonwritescode** [comment]
Sike! ;)

**Comment by littleskunk** [comment]
Next problem on mac comes after the download. Sorry my fault. Next time i should test the hotfix some minutes more. As far as i can see the download worked but the version check did not. Error message something with "Invalid dataserv-client". I need some more time to find the reason.

**Comment by gordonwritescode** [comment]
Tested on OSX Mac Mini with success.
