### ISSUE TITLE
Automate Windows Binaries

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#106]

**Comment by littleskunk** [comment]
Dependencies:
git
nodejs (32bit!)
NSIS
curl

**Comment by littleskunk** [comment]
I created a draft release. This step it not automated. Please don't delete the darft release. I need the id (2279428) for uploading.

This is the command for file upload:
curl -i -X POST -H "Authorization: token <insert token here>" -F "data=@DriveShare_0.4.1.exe" https://uploads.github.com/repos/Storj/driveshare-gui/releases/2279428/assets?name=test.exe

Authorization token can be generated here:
https://github.com/settings/tokens

Upload will only work once. The build script must delete the old file befor uploading a new one.

**Comment by littleskunk** [comment]
build_driveshare-gui.bat
<code>
setlocal enabledelayedexpansion
set gh_token=insert your token here
rmdir /S /Q driveshare-gui
git clone https://github.com/Storj/driveshare-gui.git
cd driveshare-gui
start /wait cmd /c npm install
start /wait cmd /c npm run release
cd releases
ren *.exe *.win32.exe
for /R %%F in (*win32.exe) do set filename=%%~nxF
curl -i -X POST -H "Authorization: token %gh_token%" -F "data=@%filename%" https://uploads.github.com/repos/Storj/driveshare-gui/releases/2279428/assets?name=%filename%
cd ../..
rmdir /S /Q driveshare-gui
<code>

Todo:
remove hardcoded release id
delete old file befor uploading a new one

Th script is good enought for the next releases. I will start working on ubuntu and osx.

**Comment by littleskunk** [comment]
The file is currupted after the upload. Something is wrong with the curl call.

**Comment by littleskunk** [comment]
Script is working now. I added some variables to build pull request as well. See https://github.com/Storj/driveshare-gui/releases/tag/untagged-73cca771a3187b368429

Todo:
remove hardcoded release id
delete old file befor uploading a new one
The script is good enought for the next releases. I will start working on ubuntu and osx.

**Comment by littleskunk** [comment]
Added nodejs upgrade command.

**Comment by littleskunk** [comment]
Script update. Release id is not hardcoded and the script deletes old binaries befor uploading a new binary.

Same solution like the osx script https://github.com/Storj/driveshare-gui/issues/107

**Comment by littleskunk** [comment]
Script is running in an endless loop with 60sec pause (as long as my pc is online). It will build and upload binaries for every pull request and pull request update.

```cmd
@echo off
rem set some variables
Setlocal EnableDelayedExpansion

set gh_token=insert your token here

:start
cls

rem get releases and pull requests from github
curl -H "Accept: application/json" -H "Authorization: token %gh_token%" https://api.github.com/repos/Storj/driveshare-gui/releases > releases.json
curl -H "Accept: application/json" -H "Authorization: token %gh_token%" https://api.github.com/repos/Storj/driveshare-gui/pulls > pulls.json

rem counting releases
type releases.json | jq ". | length" > temp.dat
set /p releases= < temp.dat
del temp.dat
set /a releases=%releases%-1

rem counting pull request
type pulls.json | jq ". | length" > temp.dat
set /p pulls= < temp.dat
del temp.dat
set /a pulls=%pulls%-1

set repeat="false"
for /L %%I in (0, 1, %pulls%) do (

	type pulls.json | jq ".[%%I].number" > temp.dat
	set /p pullnumber= < temp.dat
	del temp.dat

	type pulls.json | jq --raw-output ".[%%I].merge_commit_sha" > temp.dat
	set /p pullsha= < temp.dat
	del temp.dat

	type pulls.json | jq ".[%%I].head.repo.html_url" > temp.dat
	set /p pullrepository= < temp.dat
	del temp.dat

	type pulls.json | jq ".[%%I].head.ref" > temp.dat
	set /p pullbranch= < temp.dat
	del temp.dat

	type pulls.json | jq ".[0]"._links.comments.href > temp.dat
	set /p commenturl= < temp.dat
	del temp.dat

	set releasefound="false"
	set assetfound="false"
	for /L %%J in (0, 1, %releases%) do (

		type releases.json | jq --raw-output ".[%%J].name" > temp.dat
		set /p releasename= < temp.dat
		del temp.dat

		rem search for a release with automatic builds and pull request number
		if "!releasename!" == "automatic builds pull request !pullnumber!" (

			set releasefound="true"

			type releases.json | jq ".[%%J].id" > temp.dat
			set /p releaseid= < temp.dat
			del temp.dat

			type releases.json | jq ".[%%J].assets | length" > temp.dat
			set /p assets= < temp.dat
			del temp.dat
			set /a assets=!assets!-1

			for /L %%K in (0, 1, !assets!) do (
				type releases.json | jq --raw-output ".[%%J].assets[%%K].label" > temp.dat
				set /p assetlabel= < temp.dat
				del temp.dat

				if !assetlabel! == !pullsha! (
					set assetfound="true"
				)
			)
		)
	)
	rem create new release if not exists
	if not !releasefound! == "true" (
		echo create release automatic builds pull request !pullnumber!
		curl -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: token %gh_token%" -X POST -d "{\"tag_name\":\"\",\"name\":\"automatic builds pull request !pullnumber!\",\"draft\":true}" https://api.github.com/repos/Storj/driveshare-gui/releases | jq ".id" > temp.dat
		set /p releaseid= < temp.dat
		del temp.dat
	)
	rem create and upload a new binary if not exists
	if not !assetfound! == "true" (
		set repeat="true"

		rem delete old build files
		rmdir /S /Q driveshare-gui

		echo create and upload binary !pullrepository! !pullbranch!
		git clone "!pullrepository!" -b "!pullbranch!"
		cd driveshare-gui
		cmd /c npm install
		cmd /c npm run release

		cd releases
		ren *.exe *.win32.exe
		for /R %%F in (*win32.exe) do set filename=%%~nxF

		cd ../..
		for /L %%J in (0, 1, %releases%) do (
			for /L %%K in (0, 1, !assets!) do (
				type releases.json | jq --raw-output ".[%%J].assets[%%K].name" > temp.dat
				set /p assetname= < temp.dat
				del temp.dat

				if !assetname! == !filename! (
					type releases.json | jq --raw-output ".[%%J].assets[%%K].id" > temp.dat
				        set /p assetid= < temp.dat
				        del temp.dat
        				curl -X DELETE -H "Authorization: token %gh_token%" https://api.github.com/repos/Storj/driveshare-gui/releases/assets/!assetid!
				)
			)
		)
		cd driveshare-gui/releases

		curl -H "Accept: application/json" -H "Content-Type: application/exe" -H "Authorization: token %gh_token%" --data-binary "@!filename!" "https://uploads.github.com/repos/Storj/driveshare-gui/releases/!releaseid!/assets?name=!filename!&label=!pullsha!" > upload.json
		type upload.json | jq --raw-output ".browser_download_url" > temp.dat
		set /p downloadurl= < temp.dat
		del temp.dat

		curl -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: token %gh_token%" -X POST -d "{\"body\":\"Automatic build binary: [!filename!]^(!downloadurl!^) sha: !pullsha!\"}" !commenturl!
		cd ../..
	)
)
if not !repeat! == "true" (
	timeout /T 60
)
goto start
```

**Comment by littleskunk** [comment]
For new release binaries create a release with the name "automatic builds draft release". The script will build and upload binaries based on the release tag / base branch. This part does not track any new commits. Delete the binaries to trigger the script again.

Rename the new draft release to detach the script.

**Comment by littleskunk** [comment]
Automatic changelog is not possible because I could only generate a list of commits. Github already give us that list: https://github.com/Storj/driveshare-gui/compare/0.4.1...master

Removed hardcoded git clone and change directory. We can use the Script for other repositories as well. ```set apiurl=https://api.github.com/insert repository here``` and change the build commands.
