### ISSUE TITLE
Automate OSX binaries

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#107]

**Comment by littleskunk** [comment]
Tested with debian 8.2.0 but should work on osx as well. I will try that later.

Dependencies:
git
npm
nodejs
curl

build_driveshare-gui.sh
```bash
#!/bin/bash
gh_token=insert your token here
rm -r driveshare-gui
git clone https://github.com/Storj/driveshare-gui.git
cd driveshare-gui
npm install
npm run release
cd releases
filename=$(ls)
curl -i -X POST -H "Authorization: token $gh_token" -F "data=@$filename" https://uploads.github.com/repos/Storj/driveshare-gui/releases/2279428/assets?name=$filename
cd ../..
rm -r driveshare-gui
```

Todo:
remove hardcoded release id
delete old file befor uploading a new one

**Comment by littleskunk** [comment]
Something is wrong with the curl upload. File is currupted after upload.

**Comment by littleskunk** [comment]
updated the script but i have a bad curl version. The same file and the same command works on my windows pc. Need to read some more manuals about curl.

**Comment by littleskunk** [comment]
It works with curl 7.43.0.

**Comment by littleskunk** [comment]
Script update. Release id is not hardcoded anymore. Added new dependency jq for json bash query.

The new script reads the last release from github api. The name of the release must be "automatic builds". If it is not there the script will create a new one and use the new id.

Now we can use the current "automatic builds" release to push the magic button. Remove the not needed binaries, rename the needed binaries, add a changelog and release tag and rename it. As soon as the name is changed the script will create a new draft release for the next version.

Todo:
delete old file befor uploading a new one

**Comment by littleskunk** [comment]
Curl 7.43.0 is not working. I can install the currupted binary but i can't run it. See https://github.com/Storj/driveshare-gui/issues/116

**Comment by littleskunk** [comment]
Curl was not the problem. I execute the build script with sudo. sudo npm install and npm run release create a corrupted binary and curl only uploads the corrupted binary.

Lerned my lesseon for the next release.

**Comment by gordonwritescode** [comment]
Shiiiit. Been there. Try using NVM (linked in the README). You should never have to use `sudo` with NPM. ;)

**Comment by littleskunk** [comment]
Script will now delete the old binary befor uploading a new binary.

Todo:
osx: delete driveshare-gui folder without root permission.

**Comment by littleskunk** [comment]
Now the script can run without root permission.

**Comment by littleskunk** [comment]
https://github.com/Storj/autobin/blob/master/driveshare-gui/build-osx-binary.sh
