### ISSUE TITLE
Don't work, wont let me uninstall and not clear instructions!

### ISSUE THREAD

**Issue by unison3** [Storj/driveshare-gui#108]
Screenshot says it all;

![screenshot from 2015-12-13 13-57-07](https://cloud.githubusercontent.com/assets/9566686/11767316/7e39c012-a1a1-11e5-8d20-0b09e65d95b6.png)

I install anyway and it seems to complete, it appears in the dash but the first time I tried it it caused a system error and I sent a report and from that point on it does nothing when I click on the icon in the dash...

also there is only a reinstall button and no uninstall button so I have no way of knowing how to remove it without instructions... I tried all different variations of running it from the terminal but "no such command/s" exist... 

![screenshot from 2015-12-13 13-59-29](https://cloud.githubusercontent.com/assets/9566686/11767331/d21dddd0-a1a1-11e5-943c-1af70d86f8b3.png)

please fix these issues as they are basic requirements for a program!

Thanks

**Comment by littleskunk** [comment]
Duplicate https://github.com/Storj/driveshare-gui/issues/45

Will be fixed in the next release 0.4.2

**Comment by gordonwritescode** [comment]
This is resolved by https://github.com/Storj/driveshare-gui/pull/97. Will package release this week.

**Comment by gordonwritescode** [comment]
@unison3 also, you can uninstall like any other package simply with:

```
apt-get remove driveshare
```

(In the forthcoming 0.4.2 release)
