### ISSUE TITLE
OS X 10.10.5 Driveshare freezes shortly after startup first time initialization

### ISSUE THREAD

**Issue by songproducer** [Storj/driveshare-gui#121]
Tried 3 times and waited for over 10 minutes. Get's stuck downloading. Solved on the 4th time by reloading from the view menu.

**Comment by gordonwritescode** [comment]
Unable to reproduce on OSX 10.10.5. Tried >10 fresh installs. I'd chalk this up to potential GitHub availability issues during the time this was experienced.

Please reopen if you experience this again.
