### ISSUE TITLE
Updated to the .4.2 mac and keep getting this issue when I try to run

### ISSUE THREAD

**Issue by DannyDesert** [Storj/driveshare-gui#126]
![screen shot 2015-12-19 at 15 40 51](https://cloud.githubusercontent.com/assets/6620224/11915685/4c332b1a-a667-11e5-999b-6f6d04721d5e.png)

I also can't get the logs

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/driveshare-gui/issues/120
