### ISSUE TITLE
Error in OSX 10.11.2

### ISSUE THREAD

**Issue by kstarev** [Storj/driveshare-gui#127]
The app starts up, but when I click on start I get these messages.
I am running version 0.4.2.

![screen shot 2015-12-20 at 10 42 12 am](https://cloud.githubusercontent.com/assets/16372698/11918607/682f2edc-a706-11e5-8f36-a027aec35488.png)

![screen shot 2015-12-20 at 10 42 26 am](https://cloud.githubusercontent.com/assets/16372698/11918608/6dbfcc1c-a706-11e5-918d-b046aba5e9ed.png)

**Comment by ShaunHoyes** [comment]
I get the same message when running version 0.4.2 also. I tried running Driveshare a few weeks ago, and it was unable to tell me the amount of free space I had. Now I get a specific figure - which is an improvement.

**Comment by super3** [comment]
@ShaunHoyes @kstarev Fixed. Will go out in the next release.

**Comment by kstarev** [comment]
Perfect! Thanks.
