### ISSUE TITLE
No Entry Point (GetCurrentProcessExplicityAppUserModelID) on windows vista.  

### ISSUE THREAD

**Issue by bmschwa** [Storj/driveshare-gui#149]
I just installed v 4.1 of driveshare on an older computer.  I got the following dynamic link error.  Details of the machine is also included.

![capture](https://cloud.githubusercontent.com/assets/1096805/12072219/fed8f254-b099-11e5-87bb-5b912bffb646.JPG)
Details about the system:
![captureii](https://cloud.githubusercontent.com/assets/1096805/12072223/2213b13c-b09a-11e5-9ece-ecf04f1b78ef.JPG)

**Comment by littleskunk** [comment]
Sorry. Windows vista is not supported: https://github.com/atom/electron/blob/master/docs/tutorial/supported-platforms.md

You can download and run dataserv-client. Driveshare-gui is running dataserv-client in the background. https://github.com/Storj/dataserv-client/releases
