### ISSUE TITLE
Prevent duplicate driveshare-gui instance

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#151]
Minimize to windows tray. Windows will hide the icon in a drop down menu (default). Forget that you already have a running driveshare-gui instance and start a new one. Now we have a problem. 2 running driveshare-gui instances at the same time. 

I would prefer an exception message that driveshare-gui is already running. It could open the running instance but with the same exception message. If the other process freezed for some reasons i would only see the error message. I can kill the freezed process.

**Comment by littleskunk** [comment]
Same problem if I dock the icon to the task bar and minimize it to the system tray. One click on the task bar icon and windows will open an other driveshare-gui instance.

**Comment by gordonwritescode** [comment]
This should be included in @mrfancymonocle PR --> https://github.com/MrFancyMonocle/driveshare-gui/pull/2

**Comment by littleskunk** [comment]
As far as i can see it is the branch from https://github.com/Storj/driveshare-gui/pull/154

Tested it with the windows binary but it doesn't work. I can open 2 driveshare-gui instances. Same problem with ubuntu.

It works on osx.

**Comment by littleskunk** [comment]
Label Drive Share GUI v0.5? As far as i can see this is missing in v0.5. Go live anyway? I vote for yes.

**Comment by gordonwritescode** [comment]
Yes, :shipit: :)

**Comment by super3** [comment]
![http://www.troll.me/images/bush/looks-good-to-me-ship-it.jpg](http://www.troll.me/images/bush/looks-good-to-me-ship-it.jpg)

**Comment by super3** [comment]
Look like I encountered this as well. Didn't see a running version, and accidentally launched a 2nd version. This should be partly solved by #159 which will keep it in tray always, so I can see if there is a version running.

**Comment by MrFancyMonocle** [comment]
Fix in pull #163

**Comment by littleskunk** [comment]
Retest with autobin binaries for develop branch passed. I was not able to start a second process on windows, ubuntu and osx.
