### ISSUE TITLE
driveshare-gui v0.5.0 not working on linux after minimized to tray

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#156]
Tested with ubuntu (gnome) and autobin draft release develop branch.

I send the gui to tray but i can't see any tray icon. The gui is running somewhere in the background and i can't restore it. I can't open a new instance. Only way to fix that is a system restart. Sorry I can't release it with that bug.

**Comment by gordonwritescode** [comment]
What version of GNOME are you running? GNOME has two trays (silly). On 3.8+ I believe you move cursor to bottom left corner to open tray, pervious versions you will move cursor to the bottom of the screen to open tray. 

The top bar in GNOME is reserved for GNOME extensions.

**Comment by gordonwritescode** [comment]
@littleskunk Press `Super+M` to open the tray in GNOME:

![screenshot-20160106-12 26 04](https://cloud.githubusercontent.com/assets/1188875/12149289/efbd24ea-b470-11e5-979c-56f1a4ee44da.png)

**Comment by super3** [comment]
@littleskunk Seems to be the expected behavior. You can reopen if this is not the case.

**Comment by littleskunk** [comment]
Sorry that was a typical user error in more than one point. I am using the ubuntu dektop manager. It comes without a system tray.
Installed gnome and now i can see the system tray icon :)
