### ISSUE TITLE
It doesn't work on Windows 7 Ultimate 64bit

### ISSUE THREAD

**Issue by pitrov** [Storj/driveshare-gui#164]
v0.5.0.win32
After installation error occured:
![capture](https://cloud.githubusercontent.com/assets/2178987/12220911/4db4b41e-b796-11e5-9ffc-4315cb8dd255.PNG)

PS: Guys, does anybody testing it on Windows platform ? I can't run it from v0.3 :(

**Comment by littleskunk** [comment]
Yes i tested it on every platform but i did not check the config migration for any older version. I only did a test with v0.4 to v0.5.

Now you have to options. You can delete your config file %appdata%\Roaming\DriveShare\config.json and start with a new one or add your config here (remove your private information) and i will repair the config for you.

**Comment by pitrov** [comment]
It was settings.json. I removed it and all works fine ! Thank you!
