### ISSUE TITLE
User onboarding

### ISSUE THREAD

**Issue by Paalt** [Storj/driveshare-gui#167]
My opinion is that its ok to use external wallets, but there must be a much stronger guidance for the user on explaining what a wallet is, how does it work, how do I get one, and where do I find the address. My suggestion would be to make the process step based in the GUI. 
Step 1 - Wallet:
Substeps:
- you get the explanation why you need a wallet
- you get instructions of what wallets DriveShare supports
- you get instructions on how to set up the wallet and where to get the wallet adress.
- you are told where you end up when you click the link that takes you to the sign up and to come back with the address.

Step 2 - Folder:
Substeps:
- you ask the user to select a folder for storage, explain files will be encrypted
- ask for a limit on the storage, explain that disk will have to be online

Power it up!

**Comment by super3** [comment]
This is already covered by #118. We will make the experience easier with time, but with 1.6 PB of supply and no demand this is low priority for now.
