### ISSUE TITLE
Missing "New Folder" in file selector for Mac

### ISSUE THREAD

**Issue by Paalt** [Storj/driveshare-gui#168]
When I click "Browse" a file selector is opened. However, the selector is missing a "New folder" button. So the user will have to close the dialog, go to finder, make a new folder, go back to the application, relaunch the file selector and choose the folder.

**Comment by super3** [comment]
@Paalt Right click 'Create a New Folder', was able to test this out on our office Mac.

**Comment by Paalt** [comment]
Not on my mac?
<img width="919" alt="screenshot 2016-01-12 00 36 10" src="https://cloud.githubusercontent.com/assets/6736911/12250096/c37b7b18-b8c4-11e5-97f3-76ab0866109f.png">

OSX El Capitan 10.11.2

**Comment by gordonwritescode** [comment]
I think this out of scope for driveshare, as we use electron's APIs to open the native system filepicker. I'd suggest opening an issue there (or we can do so).
