### ISSUE TITLE
Everytime I load up and try and start driveshare it fails

### ISSUE THREAD

**Issue by DannyDesert** [Storj/driveshare-gui#169]
I'm on a MAC and when I run driveshare I get this message

Been happening for the last builds, never happened before, can't run the log debug afterwards either.

![screen shot 2016-01-12 at 13 44 51](https://cloud.githubusercontent.com/assets/6620224/12277869/bd864206-b932-11e5-8352-1879b35ad5ae.png)

**Comment by littleskunk** [comment]
Duplicate https://github.com/Storj/driveshare-gui/issues/120
