### ISSUE TITLE
DriveShare.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by wongtkk** [Storj/driveshare-gui#171]
After installing and starting the program that first time, this prompt is displayed:

The Procedure entry point SetCurrentProcessExplicitAppUserModelID could not be located int he dynamic link library SHELL32.dll.

**Comment by super3** [comment]
Can you tell us a little bit more about the setup/system/OS you are using?

**Comment by wongtkk** [comment]
Sorry about that! I think it has to do with the windows being 64-bit.

Windows Vista 64-bit
AMD Athlon II 160u
ram 6gbs 1333
radeon 5830 
2x 500gbs hdd

**Comment by littleskunk** [comment]
Windows Vista is not supported. https://github.com/atom/electron/blob/master/docs/tutorial/supported-platforms.md

You can run dataserv-client without the gui.
