### ISSUE TITLE
WARNING dataserv_client.messaging 61

### ISSUE THREAD

**Issue by thicaminha** [Storj/driveshare-gui#172]
I'm having an error related to my device clock sync even though it being synchronized with a NTP server.

I'm using Windows 8.1 Enterprise Edition

Log:

"2016-01-14 10:00:52,846 WARNING dataserv_client.messaging 61: Invalid authentication headers. Synchronize your clock with an internet-based time server.

2016-01-14 10:00:52,846 INFO dataserv_client.messaging 75: Query retry in 30 seconds."

**Comment by littleskunk** [comment]
Please synchronize your clock again and this time don't use the microsoft NTP server. You have to press the synchronize now button. Otherwise windows will only synchronize once a week even if you change the NTP server.
