### ISSUE TITLE
Everytime I load up and try and start driveshare it fails

### ISSUE THREAD

**Issue by DannyDesert** [Storj/driveshare-gui#173]
For the past two builds, I can't get program to run.  It always says invalid console. I'm on the mac version.  I've deleted and reinstalled the program numerous times.  What should I do?

**Comment by DannyDesert** [comment]
![screen shot 2016-01-16 at 12 42 18](https://cloud.githubusercontent.com/assets/6620224/12374377/9a68c1f8-bc4e-11e5-8aeb-d9f300490874.png)

**Comment by littleskunk** [comment]
Duplicate https://github.com/Storj/driveshare-gui/issues/120

**Comment by DannyDesert** [comment]
thanks got it fixed
