### ISSUE TITLE
Provide 32-bit .deb installer

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/driveshare-gui#176]
I hope this can happen at some point in your development process. For all of us who have old Linux machines around on which we could run DriveShare.

Personally, I have a ton of unused drive space on older machines I've rescued from the Windows graveyard by installing Ubuntu and Linux Mint on them. I would love to put them to good use for Storj testing.

**Comment by super3** [comment]
Getting a universal binary for Linux is a bit difficult. At some point we will add it as an apt package, but not while we are still doing a lot of work on it. 

See the README. You should be able to get it working with 3 commands on Linux systems:
```
git clone https://github.com/Storj/driveshare-gui.git && cd driveshare-gui
npm install
npm start
```
