### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ELQET** [Storj/driveshare-gui#178]
![default net_update_error](https://cloud.githubusercontent.com/assets/6269862/12610630/1dea4b6c-c4e9-11e5-8136-0881457856cf.png)
I have new installed Windows 8 Pro but first time I have tried to install Driveshare GUI it wanted .NET update but that crashed with exception - > screenshot. All other new drivers and application installed without any problems. So I go back to command line because of that error. But command line dataserv-client seems to be different from linux one.

**Comment by super3** [comment]
Can you paste the error text here? It's not english so I'm not sure what it says. Looks like an installer for .NET and not an error to me.

**Comment by ELQET** [comment]
There is error code 0x800F0906 and message is the same as here:
https://support.microsoft.com/en-us/kb/2734782
but strange is that this message I had only with driveshare GUI. But after while Windows installed new updates and everything is ok now. So I suppose you can close this bug. It is Microsoft Windows .NET fault. But you can investigate more if you have time.

**Comment by super3** [comment]
Glad it was resolved. Happy farming!
