### ISSUE TITLE
DriveShare Error Message

### ISSUE THREAD

**Issue by seafarer124** [Storj/driveshare-gui#179]
Loaded DriveShare for first time.  Closed and returned later to open and error message appears.
![driveshare](https://cloud.githubusercontent.com/assets/6613997/12635480/558c5ace-c5b6-11e5-9087-2a94ab0e3079.PNG)

**Comment by littleskunk** [comment]
%appdata%/driveshare/settings.json would be nice. You can remove your private information.

**Comment by seafarer124** [comment]
Hi,

I have entered "%appdata%/driveshare/settings.json", all that comes up is
the box below.

As I mentioned I am not not technically familiar with these issues.

Thanks,
Derek

[image: Inline image 1]

**Comment by littleskunk** [comment]
As far as i can read on slack your problem is solved?
