### ISSUE TITLE
Unable to start sharing due to "ImportError: No module named storjkademlia.node"

### ISSUE THREAD

**Issue by martinbehrens** [Storj/driveshare-gui#182]
When trying to start sharing a drive Driveshare.gui throws the following: "ImportError: No module named storjkademlia.node":

![screenshot-02072016-041105pm](https://cloud.githubusercontent.com/assets/2241794/12874387/5f6989f2-cdd3-11e5-8ab4-f14e1f882a90.png)

The above is true for Ubuntu 14.04 LTS Linux 3.13.0-77-generic #121-Ubuntu SMP x86_64 GNU/Linux.

Steps to reproduce:
0. Install git and nodejs-legacy.
1. Check out master branch from github,
2. proceed with npm install && npm start
3. Start of Driveshare.gui will fail due to missing dependencies and a hint to use the packaged version. Unfortunately logs didn't tell which dependencies were missing, so I had to download and install https://github.com/Storj/driveshare-gui/releases/download/0.5.0/driveshare_0.5.0.amd64.deb which finished successfully (and seems to resolve the missing dependency issue).
4. Now both, the checked out version and the amd64.deb package start successfully but throw an error "ImportError: No module named storjkademlia.node" when trying to start farming by pressing "Start" (after mandatory information has been provided).
 

p.s.: I think the error thrown got confirmed by ehmdjii in chat (although steps to reproduce might have been different):
[9:33 AM] good, morning, i still get this error when i try to run the linux command line
[9:33] ImportError: No module named storjkademlia.node
[9:33] i believe i have followed all the instructions

**Comment by Velociraptor85** [comment]
HI!
I did my Setup as written here https://github.com/Storj/dataserv-client#linux-ubuntumintdebian but I get the same error as you.

For me it Seems like it does not find the storjkademlia.node at least this is what it says and it also does not exist in dist-packages

Tried it on an Debian Jessie with python 2.7 on it

**Comment by littleskunk** [comment]
Missing requirement in storjnode 0.0.20. The bug is fixed in the next versin. For the moment please install storjkademlia yourself.
```
pip install storjkademlia
```

Should work for dataserv-client and driveshare-gui.

**Comment by Velociraptor85** [comment]
Workaround works thanks

**Comment by martinbehrens** [comment]
Confirmed, working fine.
