### ISSUE TITLE
Invalid authentication headers - Synchronize your clock (Dataserv-client Windows binary openssl hotfix)

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#191]
https://github.com/Storj/dataserv-client/issues/178
https://github.com/F483/btctxstore/issues/12
The dataserv-client binary is to old for the performance fix. We need a new binary that includes the btctxstore fix. 

I will take the 2.1.12 release tag and no code change. That is the easy way without config migration etc.

**Comment by littleskunk** [comment]
At the moment not possible for windows and osx because the openssl implementation is linux only at he moment. See https://github.com/richardkiss/pycoin/issues/176

I have to open a pull request for pycoin first to fix that problem. I will not wait for a new pycoin release. I will use the pull request for the binary.

**Comment by littleskunk** [comment]
Hotfix uploaded here:
https://github.com/Storj/dataserv-client/releases/tag/v2.1.12

To enable the performance fix you have to set a environment variable `PYCOIN_NATIVE=openssl` and install openssl for windows. I installed Win32 OpenSSL v1.0.2f Light from this side:
https://slproweb.com/products/Win32OpenSSL.html

**Comment by bedavidsson** [comment]
when i do "set PYCOIN_NATIVE=openssl" in cmd on windows 10 and then start my farmer i get this I:\dataserv-2.03\dataserv-client>dataserv-client --debug --store_path H:\STORJ\ --max_size=3276544650773 farm
C:\Program Files (x86)\Intel\iCLS Client\libeay32.dll
<CDLL 'C:\Program Files (x86)\Intel\iCLS Client\libeay32.dll', handle 30a0000 at 2eb2a90>
2016-03-06 17:34:34,697 INFO dataserv_client.messaging 47: Query: http://status.driveshare.org/api/address

**Comment by littleskunk** [comment]
Sorry my fault. I missed some debug outputs. Openssl library loaded and the hotfix is working. Otherwise the output would be `None`

I will not build a new binary. The debug output will help everyone to check that openssl is installed correct. Thank you for the feedback. Issue closed.
