### ISSUE TITLE
Add Self Reporting Spec

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/driveshare-gui#193]
Moved from @super3 https://github.com/Storj/node-storj/issues/36

---

### Self Reporting
In order to make sure that information about nodes in the network is accurate, we ask users to voluntarily self report. For example, if a node is behind a firewall and not reachable via P2P connection, we can know that they exist and there is an issue. 

Two public keys are provided. The first is used to encrypt the Node ID and IP address of the users. The second is used to encrypt the payment address. This allows a system to collect information and transparently display information without exposing the security and privacy of the users. 

Keys are delivered in this format:

      { 
            "key1": hex, 
            "key2": hex
      }

The standard format for such a self reporting message is as follows: 

    { 
      "store" : { 
        "free": int, 
        "used": int
      }, 
      "bandwidth": {
        "upload": float,
        "download": float
      }, 
      "node": {
        "id": key1(hex),
        "ip": key1(string),
        "port": int
      },
      "payment": key2(address), 
      "signature": sigdata 
    }

Signature is of the json serialized data (minus signature) with keys ordered alphanumerically. Note that a message is considered invalid and dropped if the signature incorrect or the listed IP does not match the IP of the sender.

**Comment by super3** [comment]
@gordonwritescode Do you have enough information to be able to reasonably implement this client side?

**Comment by gordonwritescode** [comment]
Just a couple modifications to the format - let's wrap it in JSON-RPC to keep things consistent, include a timestamp so the signature cannot be reused (the service can check the current time), change `node` to `contact` to be more consistent with the protocol, and `store` to `storage` (for clarity - store can be a verb):

```
{
  "id": String(message_id),
  "method": "REPORT",
  "params": { 
    "storage" : { 
      "free": Number(drive_size_bytes), 
      "used": Number(shard_dir_size_bytes)
    }, 
    "bandwidth": {
      "upload": Number(upload_speed),
      "download": Number(download_speed)
    }, 
    "contact": {
      "protocol": String(semver_tag),
      "nodeID": String(pubkeyhash),
      "address": String(ip_domain_or_host),
      "port": Number(port)
    },
    "timestamp": Date(unix_time),
    "payment": String(encrypted_payment_address), 
    "signature": String(hex_ecdsa_signature)
  }
}
```

Service should respond with JSON-RPC format:

```
{
  "id": String(message_id),
  "result": {
    // ...
  }
}
```

Or if there is an error:

```
{
  "id": String(message_id),
  "result": {
    // ...
  },
  "error": {
    "code": Number(error_code),
    "message": String(error_description)
  }
}
```

**Comment by F483** [comment]
The encryption method/curve needs to be defined. ECIES with secp256k1 (bitcoin curve) is fine by me.

**Comment by F483** [comment]
@super3 @gordonwritescode we also need to define signing, bitcoin signing is different from normal signing (adds a magic constant to the digest before signing).

**Comment by gordonwritescode** [comment]
@F483 I've implemented bitcoin style signing

**Comment by gordonwritescode** [comment]
Closing this issue, because the implementation in driveshare (develop branch) is complete. Will open a separate issue for performing bandwidth test.

Feel free to continue to use the issue for discussion.

**Comment by F483** [comment]
In adding it to the python implementation I noticed a few undefined points.

 * What is the id format (I assumed random 32bytes hex encoded)
 * What is the date format (I assumed [ISO 8601](http://stackoverflow.com/a/15952652))?

**Comment by F483** [comment]
I also assumed the encrypted_payment_address is hex encoded.
