### ISSUE TITLE
Initial result 

### ISSUE THREAD

**Issue by ubronan** [Storj/driveshare-gui#30]
I started testing the alpha test program on another machine : windows 10 x64, intel i4770, 16 Gb ram, 256 Gb boot SSD, 6 TB data disk
By letting a family member with no pc experience install this alpha, wanted to see how far he could get it working
The first problem he encountered was that after the download the program was seen as illegal program, So it needs to be allowed anyway and need to be mentioned how to handle this.
That took some explaining next hurdle was he instant started the program after the download, which ofcourse was started as a normal user.
This resulted the program to hang when it wanted to install the data-serv components.
After i set it to start as administrator the install ran fine till the size and address where added that went perfect and showed that it had succesfully made the config file.
After that the program hang at message installing... nothing happened for 15 minutes. So i told him to kill it.
Then i told him to boldly restart the program which posed another problem he could not find how to restart the program because no icon or link had been made either on dekstop nor in the start menu.
So i made it for him after that he had to press the start button after that he and i saw the build really started.So some hurdles to take but looks as a very promising result 
Only made a 200 Gb test on the data disk so no problems with rights on that.
But i think when people try to use their boot drive will give some permission issues if not build in the %appdata% directory.

**Comment by gamedevsam** [comment]
What version of the program were you running? Was it on Windows?

Everything the app is storing occurs in the %appdata% directory, the latest version shouldn't require administrator permissions in order to run on windows. Although I definitely understand the magnitude of this issue, and will work to add more safeguards to prevent hanging during setup.

**Comment by ubronan** [comment]
Answered on slack just received the update from 0.2.2 to 0.2.3
Keep up the good work
Request for option to add the program to be auto started when windows has decided to update again and does a forced reboot
Maybe an option to instant auto start farming would please alot of people as well.
I have been asking developers also to add error logging as another option which could be handy, not sure when/if will be added to the main data-serv.
