### ISSUE TITLE
Got the GUI up and running but...

### ISSUE THREAD

**Issue by DannyDesert** [Storj/driveshare-gui#39]
It's stuck on the "Performing first time initialization, please wait... Download complete, installing" screen.  I can click out of it and get to the GUI but once I but all the information in I can't hit the start button.  it has a red circle with a line through it for the cursor.

**Comment by gamedevsam** [comment]
What platform are you on?

**Comment by DannyDesert** [comment]
I'm on Mac, I was the guy taking about it on Slack yesterday

**Comment by 2Fast2BCn** [comment]
I have the same problem here (Windows 7).
Console logs are empty for me.

**Comment by 2Fast2BCn** [comment]
Not sure what happened but today it's working (it downloaded a new version upon boot)

**Comment by boshevski** [comment]
@DannyDesert can you please update and check again please?

**Comment by super3** [comment]
There have been some major updates since this was reported. If it occurs again please open an issue, and we will get to it ASAP.
