### ISSUE TITLE
Mac GUI up and running but...

### ISSUE THREAD

**Issue by DannyDesert** [Storj/driveshare-gui#40]
DLed the new GUI got it up and running, but my address is not listed on the driveshare list and it is building shards in the fold. When it crashes I have to build in a different folder and delete those shards and go back to my old folder to keep the build going.

**Comment by littleskunk** [comment]
dannydesert [03:30] 
@tome is just crashed again

dannydesert [03:30]
here is the script from the end

dannydesert [03:30]03:30
Nov 11 18:28:55 Cameron.local dataserv-client[3514] <Notice>: INFO dataserv_client.builder 131: Saving seed b92e0add76ff55d1526c799f656fcff35da7b14234d89b14dab0c1dd0e4a9c70 with SHA-256 hash efd268d73617f900a6a70294739fb8442912d6dc99fba8a5e6598ede2437326b.

Nov 11 18:28:56 Cameron.local dataserv-client[3514] <Notice>: INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/height/14xVnbyGPeyfKQkLdt8oV2rQyyR52NkJLP/2175

Nov 11 18:28:57 Cameron.local dataserv-client[3514] <Notice>: INFO dataserv_client.api 190: Current height at 2175.

Nov 11 18:29:13 Cameron.local dataserv-client[3514] <Notice>: ERROR dataserv_client.builder 75: Failed to write shard, will try once more! 'OSError(5, 'Input/output error')'

Nov 11 18:29:15 Cameron.local dataserv-client[3514] <Notice>: 2015-11-11 18:29:15.313 dataserv-client[3514:63042] dataserv-client Error

**Comment by littleskunk** [comment]
Problem is usualy a bad hard drive connection. USB drives or network drives sometimes loose connection for a short moment. There is already a one time recovery "Failed to write shard, will try once more!"

The big questions for me is why you can not resume from the last height. Can you write that log as well?

**Comment by DannyDesert** [comment]
I got it to start writing from the height, I was checking it wrong.  The biggest problem is that my building is not getting reported to the Drive Share website. 
exports.child 6339 terminated
/Users/troymurray/Library/Application Support/DriveShare/dataserv-client.app/Contents/MacOS/dataserv-client --store_path=/Volumes/StorJ --max_size=9TB farm
Nov 12 11:55:45 Cameron.local dataserv-client[6353] <Notice>: INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/address

Nov 12 11:55:46 Cameron.local dataserv-client[6353] <Notice>: INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/register/14xVnbyGPeyfKQkLdt8oV2rQyyR52NkJLP/1KPVor6JAxfgS5CPURvtA4BuW2UyLHgRrF

Nov 12 11:55:48 Cameron.local dataserv-client[6353] <Notice>: INFO dataserv_client.api 175: Starting build

Nov 12 11:55:48 Cameron.local dataserv-client[6353] <Notice>: INFO dataserv_client.builder 108: Resuming from height 8297

Nov 12 11:55:52 Cameron.local dataserv-client[6353] <Notice>: INFO dataserv_client.builder 131: Saving seed 317c4c24d76ca8940ebcc9a2dba0bb3e9153c4f8972bc175162010b482728486 with SHA-256 hash c34d5b5805ba698506c9aff2e7053f55d131ed80f379c206324465f49464f318.

exports.child 6353 terminated

I only get one QUERY and that's when it starts building

**Comment by littleskunk** [comment]
Looks like a bug in driveshare-gui. Workaround for now. Use dataserv-client without driveshare-gui until this bug is fixed.

**Comment by gamedevsam** [comment]
Can you explain what the bug is? I'm a bit confused here.

**Comment by DannyDesert** [comment]
Gamedevsam?  What don't you understand.  The GUI doesn't send my address to the driveshare page so the system doesn't think I'm running anything.

**Comment by gamedevsam** [comment]
The GUI simply stores your address in a config file and passes it off to dataserv-client when you run the process. Could you click on "View Logs" and copy and paste what you see in that window after you click the Start button?

**Comment by super3** [comment]
@DannyDesert This is an issue with driveshare-client, driveshare-client is the only thing that sends your address to the page. Please open up the issue here: https://github.com/storj/dataserv-client/issues
