### ISSUE TITLE
Failed to Run

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#41]
Ran a fresh install on Windows 10. Downloaded driveshare-client then seems to have failed at running it.

```Pinging https://github.com/Storj/dataserv-client/releases/download/v2.1.4/dataserv-client-2.1.4.win32.zip
Received response, downloading... 
Download complete, extracting C:\Users\work\AppData\Roaming\DriveShare/tmp/dataserv-client.zip
Extraction complete, validating dataserv-client.exe
Error: Command failed: C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe version

C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=D:\ --max_size=2TB farm
exports.child 5856 terminated
C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=D:\ --max_size=2TB farm
exports.child 4156 terminated
C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=D:\ --max_size=2TB farm```

**Comment by gamedevsam** [comment]
32 bit or 64 bit?

**Comment by super3** [comment]
64 bit.

Shawn

On Fri, Nov 13, 2015 at 11:07 AM, Samuel Batista <notifications@github.com>
wrote:

> 32 bit or 64 bit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Storj/driveshare-gui/issues/41#issuecomment-156474595>
> .
>



-- 
Shawn Wilkinson
Lead Developer and Founder | storj.io
me@super3.org | super3.org

**Comment by littleskunk** [comment]
Please install microsoft visual c++ 2010 redistributable package and try again. I gues you will need the 32bit package.

**Comment by gamedevsam** [comment]
I guess we need to ask users to install the redistributable package? Is this something we could automate?

**Comment by super3** [comment]
@littleskunk I think it prompted me to install that. The free space showed 0 till that installed. Its worth noting that the GUI ran fine, I was able to select everything and start it. Just it didn't do anything after its started.

**Comment by littleskunk** [comment]
At the moment driveshare-gui schould only promt you to install dot net framework and not the microsoft visual c++ 2010 redistributable package. It is needed to run python3.4 binaries (dataserv-client). Your log looks like dataserv-client did not run.

Please install it and try again. Better install the 32 bit version.

**Comment by gamedevsam** [comment]
I added an error dialog to instruct users to download .NET Framework.
![2015-11-14_1141](https://cloud.githubusercontent.com/assets/420996/11164667/d77c4b8e-8ac4-11e5-8d23-f1484317c83c.png)
