### ISSUE TITLE
v0.3.4-alpha browse and start buttons do nothing

### ISSUE THREAD

**Issue by heunland** [Storj/driveshare-gui#42]
On v0.3.4 running on windows 7, I cannot choose a storage location with the browse button. It does not react to clicking it. Also once I filled in the path to my storage location, I click the start button and nothing happens. So I cannot start the driveshare at all. In the previous version 0.3.3 I was able to run driveshare but after it stopped working (my computer was unexpectedly shut down), the next time I opened it, it prefilled the wrong payout address by default which I didn´t notice, so I accidentally started building a new build, and after a short time noticed I was running out of space on my hard disk. This necessitated me deleting all the files of my prior build and starting over. Then when I started building with the right address again, I noticed the shards don´t actually get stored in the directory I had selected: C:/Storj/data, but a new subdirectory was created here: C:\VTRoot\HarddiskVolume2\Storj\data and all the shards where written to that directory instead.

**Comment by heunland** [comment]
I closed the driveshare-gui and opened it again, after which I was again presented with a prefilled screen with the wrong payout address as in v0.3.3 before. So I substituted with the correct address, and was now able to properly configure all the options and start Driveshare. Interestingly enough, this time it again started building from scratch, but on the actual directory I had specified as storage location.So again I was forced to delete all my shards that were stored in  C:\VTRoot\HarddiskVolume2\Storj\data and now I have to wait for the build to rebuild from the beginning for the second time in one day. So, far from making running driveshare easier, this just wasted most of my day in unnecessarily rebuilding my build twice. It is alpha software so I am not complaining but I hope you can fix this so that people don´t loose their builds accidentally.

**Comment by super3** [comment]
@heunland Could you please copy-paste the full log here.

**Comment by heunland** [comment]
Sorry I cannot recreate the error log now cause I gave up using the GUI and went back to the command prompt method.
