### ISSUE TITLE
Dependency Mismatch

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#46]
[project:sm]
```Obtaining download URL for dataserv-client
Downloading https://github.com/Storj/dataserv-client/releases/download/v2.1.4/dataserv-client-2.1.4.win32.zip
Download complete, extracting C:\Users\work\AppData\Roaming\DriveShare/tmp/dataserv-client.zip
Extraction complete, validating dataserv-client
Error: Command failed: C:\Users\work\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe version
Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 188, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 68, in __init__
  File "E:\dataserv-client\dataserv_client\control\config.py", line 60, in get
  File "E:\dataserv-client\dataserv_client\control\config.py", line 103, in migrate
KeyError: '2.1.11'
```
Not exactly sure how this is happening as it clearly says its download 2.1.4, but seems to try to run 2.1.11. DriveShare-GUI should be running the latest version which is 2.1.11.

**Comment by super3** [comment]
@gamedevsam Could you please have DriveShare GUI run version 2.1.11 of DataServ-Client.

**Comment by littleskunk** [comment]
@super3 
New version 2.1.11 is draft. Latest binary release is 2.1.4. As soon as somebody press the release button driveshare-gui will download it.

Better wait ~4h with the 2.1.11 release. I did not try driveshare-gui with the new dataserv-client version. I will do that as soon as i am at home.
