### ISSUE TITLE
Missing Drive #1 config after update

### ISSUE THREAD

**Issue by jdogresorg** [Storj/driveshare-gui#48]
This morning I ran 'git pull' to update my driveshare-gui code, then I started up driveshare and instead of seeing my settings populated as I did previously, all fields are blank.

![https://gyazo.com/126bca8610833a089b7f63431c02db53.png](https://gyazo.com/126bca8610833a089b7f63431c02db53.png)

Should the previous config appear in the "Drive #1" settings?

Any idea where the previous versions config data was saved? I had some custom height and I don't really feel like building for multiple days again ;)

**Comment by super3** [comment]
@djandreski Looks like the multi-drive setup might have broken compatibility with older vision settings.

**Comment by djandreski** [comment]
new "npm install" needs to be run, and yeah, the settings have a slightly changed format, so I you need to reconfigure the client

**Comment by jdogresorg** [comment]
Where can I locate the old settings? my payout address, height, etc?

**Comment by gamedevsam** [comment]
In your user data directory:

On Windows:
```C:\Users\sbatista\AppData\Roaming\DriveShare``` or ```C:\Users\sbatista\AppData\Roaming\DriveShare_Dev```

**Comment by jdogresorg** [comment]
Thanks, but I was asking about OSX (Mac), as I don't run windows.

**Comment by gamedevsam** [comment]
On Mac:
```~/Library/Application Support/DriveShare``` or ```~/Library/Application Support/DriveShare_Dev```

See [this link](http://www.macworld.com/article/2057221/how-to-view-the-library-folder-in-mavericks.html) if you can't find the Library folder.

PS: Look for a file titled: settings.json

**Comment by jdogresorg** [comment]
Thanks.
