### ISSUE TITLE
Payout address

### ISSUE THREAD

**Issue by nelsonpk** [Storj/driveshare-gui#55]
There appears to be something quaint about the driveshare GUI app: I was running 4 builds (3 through the command line (DOS shell) and one through the driveshare GUI - all were to the same payout address 15qNBRy6RC176tuxC6kaWUBWdKTysJpQyc.This was done by having discreet users on a windows machine. This generated something like 35TB of space. I then deleted all of the shards on the GUI build and the config files and attempted to rerun the driveshare GUI to a new payout address 1gyqRBeg6zvjfH5EQa1Y5krnUnjuCXaxQ, but every time I tried to start the GUI version it reverted to the old payout address and the config file showed a wallet address that I didn't recognise and the new payout address didn't show in http://status.driveshare.org/api/online. I've now restarted the build of this 4th one through a command line and everything appears normal again. Any clues - it's almost as though the payout address is hardcoded into the GUI, unless I'm missing something?

**Comment by super3** [comment]
@nelsonpk So the GUI has its own config file separate from dataserv-client. What you did is delete the dataserv-client config, but not the GUI config. This would generate a new address each time, but keep all the payout stuff in the GUI.
