### ISSUE TITLE
 windows-10 HTTP errors

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/driveshare-gui#56]
Running on 2 of my windows 10 machines i get lots off HTTP errors.

dataserv-client version 2.1.4

C:\Users\Meije\AppData\Roaming\DriveShare/dataserv-client/dataserv-client.exe --store_path=C:\Users\Meije\Desktop\GUI data --max_size=1GB farm
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/address

INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/register/17hALFihy5gCPDMHUyzu6Cm9dxoPAMk2Uj/1DPE45e4o4LiiTNkYaNmGQ4D29oBuyszhU

INFO dataserv_client.api 175: Starting build

INFO dataserv_client.builder 108: Resuming from height 1

INFO dataserv_client.builder 131: Saving seed b77ccd1330ace5dff4b666405bd738a0769a933f77e15239f51b627f6ffafae4 with SHA-256 hash 6c482094908afc2c191709f781d9da6aa1e15ebb47f621a072fd9e0ccd3be30f.

INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/height/17hALFihy5gCPDMHUyzu6Cm9dxoPAMk2Uj/1

WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED

INFO dataserv_client.messaging 78: Query retry in 30 seconds.

INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/height/17hALFihy5gCPDMHUyzu6Cm9dxoPAMk2Uj/1

INFO dataserv_client.api 190: Current height at 1.

INFO dataserv_client.builder 131: Saving seed 258019c8cea455e931aadf6a4aa36678d4a1df54491ed6e1038cfb53478f604d with SHA-256 hash 26678fbff8c9f8af7fefef53b97adb7a2134d3f8b42ceeb69bf5f78cfe07b7e1.

INFO dataserv_client.builder 131: Saving seed 062033ad61b36049319f6d7b9b7089ad553a6b7e04034e981c4859e46417c004 with SHA-256 hash ec9c3cbc0ceb4e68b060207fb056ad5e5c96fe0a3bf21a6a80e68496a03a5b7b.

INFO dataserv_client.builder 131: Saving seed 4890c11f0f2bb47430c9eca9fccaa60e81bac82fb536c22b6cabc55fbf6c8105 with SHA-256 hash b5566ebf9b60728e4eddaf23eff419e00a76c903f62eccaa967ed9921163fe8e.

INFO dataserv_client.builder 131: Saving seed e106a655209545adb9d2b80093c52541d7a7f8db70b778030e289c27e53adbea with SHA-256 hash 996a12c9288e0108fece3792624ea078330a824054886f64802f678eb8b01644.

INFO dataserv_client.builder 131: Saving seed 1fcedc0ac73c231cf144e4fa9c5a54a450c9330d0f2a04ccbeaa9b941ecf6da6 with SHA-256 hash e794ebf5b3138e0736fcdd13e1a779b0bf0e280d4055edeafd2aa63846281e92.

INFO dataserv_client.builder 131: Saving seed a426afc03187af5fe7b2b00fba4e106c51934844539d44466b0fc6fc559b914a with SHA-256 hash 98cbc546c7e739673d816d436e86326b7fed2b354c7714daf58b979e60ed1b02.

INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/height/17hALFihy5gCPDMHUyzu6Cm9dxoPAMk2Uj/7

WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED

INFO dataserv_client.messaging 78: Query retry in 30 seconds.

INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/height/17hALFihy5gCPDMHUyzu6Cm9dxoPAMk2Uj/7

WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED

INFO dataserv_client.messaging 78: Query retry in 30 seconds.

INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/height/17hALFihy5gCPDMHUyzu6Cm9dxoPAMk2Uj/7

WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED

INFO dataserv_client.messaging 78: Query retry in 30 seconds.

**Comment by littleskunk** [comment]
Please syncronize you system clock with a time server and try again.

**Comment by MeijeSibbel** [comment]
My system clock was synchronized with the windows time server, i changed it to a different time server and it works now, thanks!
