### ISSUE TITLE
FAT32 external drive tree structure not recognized by GUI

### ISSUE THREAD

**Issue by heunland** [Storj/driveshare-gui#57]
I attempted to farm using the GUI on a windows7 desktop with attached USB external drive formatted with FAT32. The shards had already been generated before with driveshare-client v2.1.4 command prompt method and I was hoping to be able to reuse the almost 2 TB of shards with the new GUI. However, the existing directory structure is not recognized by the GUI. I thought it was supposed to detect the drive I am using is FAT32 formatted and proceed with tree structure accordingly. Luckily the existing shards resulted unharmed and I was able to start farming again with command prompt method as before without problems. Maybe the problem with the GUI is also that I previously was farming from C:\storj\dataserv_client and now the GUI is downloading and expanding into another directory C:\Users\Helene\AppData\Roaming\DriveShare/tmp/dataserv-client.zip. Here is the screenshot of my GUI setup, and the console error log that resulted:

![image](https://cloud.githubusercontent.com/assets/8723695/11446916/dc16b258-9503-11e5-8af0-f284ecf5933e.png)

![image](https://cloud.githubusercontent.com/assets/8723695/11446933/2174670a-9504-11e5-8ac2-6622b3134d67.png)

![image](https://cloud.githubusercontent.com/assets/8723695/11446936/2b22fd52-9504-11e5-9f8d-039a47500bdf.png)

![image](https://cloud.githubusercontent.com/assets/8723695/11446937/3121d462-9504-11e5-9551-30fe2c06f4db.png)

**Comment by super3** [comment]
@heunland We fixed this in dataserv-client, but looks like the GUI doesn't call that option. In the next major release we will add a checkbox for FAT32.

**Comment by heunland** [comment]
I think it would be nice to let other testers know of this limitation of the current GUI (not appropriate for use with FAT32 drives). Looking forward to the next release!

**Comment by super3** [comment]
@gordonwritescode Should tackle this when you do minimize to tray/startup. As stated in the [dataserv-client documentation](https://github.com/storj/dataserv-client#show-program-help-optional-arguments-and-commands) you need to use the ``` --use_folder_tree``` option. This should just be a checkable item in preferences.

**Comment by MrFancyMonocle** [comment]
I'm not certain that the GUI should be passing the use_folder_tree option here; to me, it seems like the dataserv-client should be determining the file system type to eliminate the need for client applications to implement various cross-platform file system detection or worse, a checkbox for a user to tell a machine about itself. Opening Issue in dataserv-client to discuss further.

**Comment by gordonwritescode** [comment]
Storjnode already implements this here: https://github.com/Storj/storjnode/blob/master/storjnode/util.py

Should be trivial to have dataserv-client do this. @mrfancymonocle

**Comment by littleskunk** [comment]
It is not that trivial as you can see. @heunland has a fat32 drive but the autodetection failed.

At the moment we can't detect fat32 drives for sure. One of the problems is: https://code.google.com/p/psutil/issues/detail?id=434

There are other possible bad setups we can't detect.

**Comment by gordonwritescode** [comment]
Oops sorry @littleskunk, I mixed up this issue with #83
