### ISSUE TITLE
[SOLVED].NET Framework

### ISSUE THREAD

**Issue by UnityX** [Storj/driveshare-gui#58]
I always get the error: There was an issue running dataserv-client, make sure you have Microsoft .NET Framework installed and try again.

I also tried reinstalling .NET Framework.

**Comment by super3** [comment]
What Microsoft OS are you running?

**Comment by UnityX** [comment]
7

**Comment by super3** [comment]
Try installing Python 3, then try again. If that doesn't work I have one
more suggestion.

Shawn

**Comment by UnityX** [comment]
Ok, i´m going to try thanks for the fast answer :)

**Comment by UnityX** [comment]
Ok it didnt work, just for you to know I´ve .NET FM 4.6 installed is that right for this to work ?

**Comment by super3** [comment]
Try this: "I was having the same issue here. In looking into this issue I found that the driveshare-gui could not find a file. The file that looks like it was missing is the "msvcr100.dll". If you install the "http://www.microsoft.com/en-us/download/details.aspx?id=26999" [Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update] "

**Comment by UnityX** [comment]
Well im going to reinstall everything and then ill try again, Ill answer to this if I finished testing.

**Comment by UnityX** [comment]
mhmm, still not working :(

**Comment by UnityX** [comment]
Ok, ive tried installing x64 2010 c++ redist. and it seems to be working o,o

**Comment by UnityX** [comment]
sorry I meant, x86

**Comment by UnityX** [comment]
And could you maybe tell me how long does it take to reserve 450gb ?

**Comment by UnityX** [comment]
So everybody having the same issue I could help to install.

http://www.microsoft.com/en-us/download/details.aspx?id=26999 x86 AND x64(Depends if you have a 64Bit system)
Phyton 3 as super3 told me to.

This is just a Overview of the suggestions super3 made for me :)

**Comment by littleskunk** [comment]
Just a short explanation. 

dataserv-client version 2.1.4
The dataserv-lient 2.1.4 binary is compiled in python3.4. To execute that binary a spezial Library msvcr100.dll is needed. That library is part of Microsoft Visual C++ 2010  Redistributable Package. 2010 Redistributable Package 64bit will not work. 32bit is needed. Redistributable Package 2015 will not work. It has to be 2010.

dataserv-client version 2.1.11 and 2.1.12 (not yet release as binary)
Newer version dont support python3 at the moment. The binary will be a python2.7 32bit binary. That needs msvcr90.dll. That library is part of Microsoft Visual C++ 2008 Redistributable Package. 64bit will not work. 32bit is needed.

@super3 
I close the bug now but if you think driveshare-gui should promt this or install it in the background please open a task for it. dataserv-client-2.1.11.python27.win32.zip would make it easy for driveshare-gui to promt the needed library.
