### ISSUE TITLE
There was an issue running dataserv-client, make sure you have Microsoft .NET Framework installed and try again. If the issue persists let us know on github.

### ISSUE THREAD

**Issue by d6dragon** [Storj/driveshare-gui#59]
Dont wonth to work on windows 7. I instal Microsoft .NET Framework and restart the computer and its the same? Please help!!!

**Comment by littleskunk** [comment]
Is it the same exception like https://github.com/Storj/driveshare-gui/issues/60

**Comment by littleskunk** [comment]
I gues its duplicate and solved with bugfix of https://github.com/Storj/driveshare-gui/issues/60
