### ISSUE TITLE
driveshare-gui doesn't work

### ISSUE THREAD

**Issue by icmos** [Storj/driveshare-gui#60]
Hi, 
I try to install the GUI and I receive this message 
"The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32bit) or x64 (64bit) version of the program, and then contact the software publisher.". 
I have already installed .NET 4.6 and Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update.
I have Win 7 32bit and I tried to install the GUI on two computers with same result. 
On one of this computers dataserv-client-2.1.4.win32 works w/o problem.

**Comment by calkob** [comment]
im having the same problem on a vista 32bit.  the dataserv-client is working fine also. ive attached a screen shot.

![driveshare error](https://cloud.githubusercontent.com/assets/16057802/11451984/1a8d0790-95d0-11e5-8b8d-cb6c20649eef.jpg)

**Comment by littleskunk** [comment]
Some other user have the same problem. I bet all of them are using a 32bit os but at leaste the windows gui looks like a 64bit binary. I will try to setup a build environment myself to create a new binary. I hope i can fix the bug.

**Comment by littleskunk** [comment]
I renamed the old binary to win64 and uploaded a win32 binary. Please try it and close the bug if it is working.

@gamedevsam Thank you for the good readme.

**Comment by littleskunk** [comment]
Default install folder is C:\Program Files (x86)\DriveShare\
I get some exception cause of the blank in the path. As workaround you should start driveshare gui from a path without blank.

**Comment by asgsch** [comment]
I have this issue also on Windows 7 (32 bit)...

**Comment by littleskunk** [comment]
The relase tag has missing files (app/node_modules/*). I cant fix the release tag but i was able to build a working win32 version. I had to copy the missing files from the master branch. As far as i can see it should work like the 64bit version. If you have any problems with 0.3.4 please let us know you are using the win32 version. Just in case the bugs you find are my fault.
