### ISSUE TITLE
Blanks in folder name

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#61]
Some user have blanks in there store_path. I did a short test with linux an windows.

dataserv-client version 2.1.11
dataserv-client.exe --store_path=D:\storj test\ --max_size=1024000000 farm

That is wrong. I would expect.
dataserv-client.exe --store_path="D:\storj test\" --max_size=1024000000 farm

The same solution works on linux as well without the drive letter ofc.

**Comment by gordonwritescode** [comment]
Node's `child_process.spawn()` will automatically escape arguments passed in, so this should be resolved by https://github.com/Storj/driveshare-gui/pull/65/files#diff-f8c0e7dbf199c360d2ba5f14a7e62a31R35

**Comment by littleskunk** [comment]
Yes the bug is fixed with your branch. I will keep that bug open until your branch is merged.

**Comment by gordonwritescode** [comment]
Okay very good. This issue is referenced there so it *should* auto close on merge. Thanks for going through this stuff with me!

**Comment by littleskunk** [comment]
fixed with driveshare-gui develop (0.4.0)
