### ISSUE TITLE
Free Space: 0.0 GB on Mac OSX

### ISSUE THREAD

**Issue by skaag** [Storj/driveshare-gui#62]
In the latest DriveShare GUI, the reported shared size is 0.0 GB. I showed the log file to @littleskunk who reported back that everything seems to be working and in order, so this is likely a visual bug only.

**Comment by littleskunk** [comment]
```DriveShare
Payout Address [...]
Balance: [...] SJCX
 Storage Location Free Space: 0.0 GB
