### ISSUE TITLE
Removing drives

### ISSUE THREAD

**Issue by boshevski** [Storj/driveshare-gui#64]
When I want to delete one drive, there is an alert dialog for confirming the action. After confirming delete, the alert pops up again for all the other drives, until there are no drives left.

**Comment by littleskunk** [comment]
Bug is fixed with that pull request. I will keep the bug open until the branch is merged.

**Comment by littleskunk** [comment]
There is a bug. I start building with 3 drives and removed the last drive while it was active. Drive number 2 gets the start button again but the process is still running in the task manager. If i start drive 2 again i get one process more.

**Comment by gordonwritescode** [comment]
Ack. Will resolve.

**Comment by gordonwritescode** [comment]
Fixed by latest #65 (mirrored on `develop`).

**Comment by littleskunk** [comment]
Sorry i have to reopen the bug.
I start building with 3 drives (0,1,2) and removed number 1 while it was active. Drive number 3 gets the start button again but the process is still running in the task manager.

**Comment by gordonwritescode** [comment]
Okay so to be clear: the GUI state is correct, but the underlying dataserv process is not terminated, yes?

**Comment by littleskunk** [comment]
GUI state is wrong. The process is still running as it should but the GUI gives me the orange start button and not the green running button. Drive number 2 is not the one i removed. The process for number 1 (the one i removed) was terminated.

**Comment by littleskunk** [comment]
Retest with gordonwritescode:bug/remove-drive passed. Bug will be closed after a short restest with the next release version.
