### ISSUE TITLE
Password in the console log

### ISSUE THREAD

**Issue by minijackson** [Storj/driveshare-gui#66]
I tried installing DriveShare in a Linux computer whose distribution is not Debian based. I was a bit concerned when I looked at the console log and found my password in plain text. Here's the log:

```bash
/bin/sh -c echo MyPassword | sudo -S apt-get install python3-pip
```

I think there's multiple issues here:

- I don't think the password should be piped to sudo. You could use the `pkexec`, `gksudo` or `kdesudo` (I have a preference for `pkexec`) like that:
```pkexec apt-get install python3-pip```
- You should be wary of any user input: If the password have a quote or a double quote in it, the command will fail trying to find a matching quote. Therefore, the input should be quoted and parsed to escape any special characters.
- It may be better to add python3-pip as a dependency in the .deb file, instead of trying to install the package at runtime: the package manager will do it nicely.
- Finally I think that you shouldn't use at all any package manager in the source code, that will make the program harder to maintain and harder to adapt to other Linux distributions.

Hope I helped and didn't offended anybody in any way.

**Comment by pallas1** [comment]
This is scary! The password will probably be visible to all the other users of the system, via a simple ps command.

**Comment by subwolf** [comment]
It will be scary if the attacker knows to monitor the computer knowing that command is being run. Any other time it won't show up, yes?

**Comment by minijackson** [comment]
The password stays on the console log. Even if the log is reset at each start, it doesn't mean that it isn't stored anywhere on the system or that an hypothetical attacker can't retrieve this information directly from the app.

**Comment by pallas1** [comment]
A plaintext password in a file and visible via ps is a hacker's dream.

**Comment by subwolf** [comment]
Should be an easy fix though, I hope.

**Comment by minijackson** [comment]
This specific issue should be easy to fix, but this could also mean that this app may need a complete security audit

**Comment by minijackson** [comment]
I should mention that this is the .deb version and not the one in the repo. It seems that the git version doesn't ask the password and doesn't work for me.

**Comment by subwolf** [comment]
The code is open for auditing any time.

**Comment by gordonwritescode** [comment]
Hi friends, I noticed this the other day. I just joined Storj and have a work in progress PR that includes a large refactor of the driveshare code. The fix for this will be included in that PR.

**Comment by subwolf** [comment]
Nice!
