### ISSUE TITLE
Automate the installation of required Windows libraries

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/driveshare-gui#69]
See https://github.com/Storj/dataserv-client/issues/13

**Comment by littleskunk** [comment]
You will need different windows libraries for different dataserv-client versions.

See last comment https://github.com/Storj/driveshare-gui/issues/58

**Comment by gordonwritescode** [comment]
Does anyone have any experience with windows package management (does that even exist?)?

Ideally, I'd like to remove dependency installation logic from the app altogether and let the system's package manager handle this stuff. 

The app builds an installer with NSIS for windows. There must be a way to list dependencies there! @super3

**Comment by gordonwritescode** [comment]
This will become obsolete after the JS implementation of the storj protocol is stable as we will no longer need any OS specific dependencies.
