### ISSUE TITLE
driveshare-gui develop (0.4.0) freeze after error message

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#75]
I start the driveshare-gui develop (0.4.0).
Payout adress is empty. I hit the start button and get a error message because of invalid payout adress. Everything fine so far. After that error i fill out everything but i cant hit the start button again. There is only a dissabled button "preparing"

![screenshot](https://cloud.githubusercontent.com/assets/6333390/11602644/1da135a8-9adc-11e5-8b8a-b8bf8e8ec2c9.jpg)

**Comment by gordonwritescode** [comment]
Ah this is an easy fix, must not be resetting the button state on error. Will squash this one Monday morning

**Comment by gordonwritescode** [comment]
Fixed by #65, mirrored on `develop`

**Comment by littleskunk** [comment]
Retest passed with driveshare-gui 0.4.1
