### ISSUE TITLE
Change payout address impossible

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#76]
I start the gui with the wrong payout address. I stoped the gui and start again with a new payout address. Everything in the gui is looking fine but my new payout address is not listet on the online list.

The reason for that is the registered auth address. There is no api call to update the payout address for the same auth address. https://github.com/Storj/dataserv-client/issues/55

Tested with 0.3.4 and 0.4.0 (develop branch)

What now? Should the gui delete the auth address to register a new payout address? That way the user will loose his uptime. We have to be carefull.

**Comment by super3** [comment]
So that is the correct design. Payout addresses are "locked" to a payout address. This is both to avoid implementing tons secure change code, but also to remove edge cases for malicious actors. 

If you need to change your payout address then you generate a new auth address.

**Comment by littleskunk** [comment]
So this is fixed in 0.4.1? It was not working in 0.4.0. I will try again and reopen the bug if needed. As long as the user can change his payout address in the gui but cant see his address at the online list i will call that a bug. We have to make the payout address at least read only.

**Comment by littleskunk** [comment]
Retest passed (gordonwritescode:bug/payout-address-change)

Fix will be in the next version after merge.
