### ISSUE TITLE
Don't quit OSX wallet on "red button".

### ISSUE THREAD

**Issue by sammy007** [Storj/driveshare-gui#77]
Not expected behaviour.

**Comment by gordonwritescode** [comment]
Hi there, can you describe the issue in more detail? What version of driveshare are you running? Can you provide steps to reproduce?

**Comment by sammy007** [comment]
Storj DriveShare version 0.3.4. Click red button on window decoration and it will completely quite app. This is usually not expected behaviour on OSX. It should stay in dock as running app and you can close it by right click and quit menuitem.

**Comment by gordonwritescode** [comment]
Ah, that clears it up, thanks!

**Comment by super3** [comment]
So this is OSX specific UI/UX behavior. Somewhat related to #89

**Comment by gordonwritescode** [comment]
Relevant: https://discuss.atom.io/t/how-to-catch-the-event-of-clicking-the-app-windows-close-button-in-electron-app/21425
