### ISSUE TITLE
Package Release

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#82]

**Comment by littleskunk** [comment]
I will be home in ~2h-3h. I can build a windows 32bit binary in minutes. We should not build a 64bit binary for windows. I see no advantage using 64bit.

I have virtual machines for debian and mac as well but https://github.com/Storj/driveshare-gui/issues/45 looks like it is not as easy as the windows binary.

**Comment by super3** [comment]
@littleskunk Ok, I've assigned you the issue. Sooner the better so we can fix issues that pop up. Windows binary first please.

**Comment by littleskunk** [comment]
Uploaded windows and mac binary. 

Debian binary is not working at the moment. I will fix that later.

**Comment by littleskunk** [comment]
Uploaded windows and mac binary 0.4.1

Linux is still a problem. I can build a binary but i am to stupid to intall it myself. Maybe its a simple user error. I will upload it later.
