### ISSUE TITLE
Free Space Not Working on Windows

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#83]

**Comment by littleskunk** [comment]
I see 2 Problems.
1.) Free space comes only if i use the browse button. If i change the store path myself without using the browse button i am getting wrong free space values.

2.) At least the browse button will display it but only if i start it myself (npm start). It is not working in the binary release. Looks like missing files. We had the same problem with the 0.3.4 release tag.

**Comment by littleskunk** [comment]
Its working on mac.

**Comment by littleskunk** [comment]
Same problem with driveshare-gui 0.4.1.

**Comment by gordonwritescode** [comment]
Strange. I bet that the build script is excluding the required .exe for windows from the release. Will investigate.

**Comment by gordonwritescode** [comment]
Okay, I dove into this one a bit on a Windows 7 VM and discovered that the `drivespace.exe` is, in fact, getting included in the release. The executable also works as documented when calling it directly from the command line. However, for whatever reason, the paired nodejs module doesn't behave when the release is packaged.

Here is a screen of me calling the node library from the packaged release and it fails, followed by calling the executable directly, succeeding.

![screenshot-20151209-01 10 29](https://cloud.githubusercontent.com/assets/1188875/11678037/22cb3356-9e12-11e5-8186-039bb758bdee.png)

Let me be the first to tell you that I *have no idea how Windows works*. Any ideas?

**Comment by gordonwritescode** [comment]
@littleskunk I fixed problem 1 FYI - see PR

Problem 2, I wrestled with for hours. Got nothing. Windows sux.

**Comment by super3** [comment]
@gordonwritescode I'd raise an issue https://github.com/keverw/diskspace.js

**Comment by super3** [comment]
Backup to this is implementing a freespace feature in dataserv-client.

**Comment by gordonwritescode** [comment]
If we can surface the free space checker in storjnode from dataserv-client, we can call it instead of using the windows specific executable here. 

https://github.com/Storj/storjnode/blob/master/storjnode/util.py
