### ISSUE TITLE
config migration not working

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#85]
Some user have problems with there old settings.json in combination with the dataserv-gui 0.4.0.

Here is the settings.json from one user:
{"dataservClient":"C:\\Users\\XXX\\AppData\\Roaming\\DriveShare/dataserv-client/dataserv-client.exe","payoutAddress":"removed","dataservDirectory":["G:\\DS3"],"dataservSize":"2.57","dataservSizeUnit":"TB"}

Workaround for other user:
Remove "[" and "]" (dataservDirectory), save it and reload the gui.

**Comment by gordonwritescode** [comment]
Aha! Nice catch @skunk - the new config expects a string for the directory path:

https://github.com/Storj/driveshare-gui/blob/master/app/lib/userdata.js#L79

Will fix in the morning.

**Comment by littleskunk** [comment]
Same problem with version 0.4.1.

**Comment by littleskunk** [comment]
Here is my config generated with driveshare-gui 0.3.4
{"dataservClient":"C:\\Users\\Skunk\\AppData\\Roaming\\DriveShare/dataserv-client/dataserv-client.exe","payoutAddress":"","dataservDirectory":["D:\\"],"dataservSize":"","dataservSizeUnit":"MB"}

**Comment by gordonwritescode** [comment]
Strange, that string is not even valid JSON. The backslash in the `dataservDirectory` value is escaping the following `"`. App crashes on launch with this config. I'm assuming/hoping that your config actually *does* have an additional `\` to escape the `\` (so meta) and it got lost in copy/paste?

**Comment by littleskunk** [comment]
Retest with gordonwritescode:bug/remove-drive passed. Bug will be closed after a short restest with the next release version.
