### ISSUE TITLE
Troubles updating GUI

### ISSUE THREAD

**Issue by ck34** [Storj/driveshare-gui#86]
Upon opening the GUI I am ask whether or not i would like to update. Whether I press yes or no it starts updating anyways, which leads to one of two outcomes.The first one being it freezes mid update and does not continue. The second one being  the update hits 100% and then comes up with the error "There was an issue running dataserv-client, make sure you have Microsoft .NET Framework installed and try again. If the issue persists let us know on github." I have tried reinstalling the Microsoft .net framework, but no luck. I am running Windows 7 professional.

**Comment by ck34** [comment]
already  solved, need microsoft c++ redistubte packe x86

**Comment by littleskunk** [comment]
Dublicate: https://github.com/Storj/driveshare-gui/issues/69

Workaround for now:
Microsoft Visual C++ 2010 Redistributable Package 32bit for dataserv-client 2.1.4
Next dataserv-client release needs Microsoft Visual C++ 2008 Redistributable Package 32bit.
