### ISSUE TITLE
Run at startup

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#88]
The app need to be able to keep track of its late "state" and re-run that state when the computer is restarted. So if I started Drives 1 and 2 and left them running, those need to start back up when the computer starts back up. 

This will require the addition of a preferences dialog and/or check box so the user can turn on/off this action. I'm thinking that this option should be on by default, but that can be debated.

**Comment by MrFancyMonocle** [comment]
Status Update: Everything appears to be working cross-OS here on my develop branch. I'm not submitting a pull for this yet, as there's a bug that would be introduced if a user switches back and forth between running the app with npm start and a release build. I'm not sure I see the reason to even have the npm start option here; what are we actually getting from manually moving files to a temp dir and throwing them at an electron instance? If we want to keep it, we'd essentially need another config file, another windows registry key for startup, etc, or the two will step on one another. Why maintain two apps?

**Comment by gordonwritescode** [comment]
> @MrFancyMonocle  I'm not sure I see the reason to even have the npm start option here

So that we don't have the build a release every time we want to test code during development.

What is the nature of the bug?
