### ISSUE TITLE
Minimize to Tray

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#89]
This will require the addition of a preferences dialog and/or check box so the user can turn on/off this action.

**Comment by MrFancyMonocle** [comment]
https://github.com/Storj/driveshare-gui/pull/125. After working on this, I think it would be beneficial to spend a few days looking at the app's data flow, as there are a few scenarios not currently covered, and I'd like to have a concrete service handling communication between threads, persistence, state, without the service being concerned about the data contents specifics.
