### ISSUE TITLE
0.4.1 fails to run on Windows Vista

### ISSUE THREAD

**Issue by phideas** [Storj/driveshare-gui#95]
I tried to install 0.4.1 on Windows Vista. Installation went good, but the app fails to run. Here the srceenshot with the error: http://imgur.com/kYk6VA7

Now I know Vista is outdated OS, but I can't change it on that machine because a licensed app runs on it and the upgrade would cost me more then the current value of that computer.

**Comment by littleskunk** [comment]
The electron framework does not support Windows Vista. You can run dataser-client without the GUI. That is the only solution at the moment.

I would call that a bug and keep it open. @super3 your turn. Maybe we should switch to a better framework. List of supported platforms you can find here. https://github.com/atom/electron/blob/master/docs/tutorial/supported-platforms.md

There are a lof of platforms that are not supported.

**Comment by phideas** [comment]
NP dataserv-client works reliably for me. Thanks!
