### ISSUE TITLE
Update dataserv-client did not work

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare-gui#96]
We released dataserv-client 2.1.12 but my windows driveshare-gui 0.4.1 is still running dataserv-client 2.1.4. I can't upgrade to the new dataserv-client version. Check for update is not working.

Workaround:
Stop driveshare-gui, delete %userprofile%\AppData\Roaming\DriveShare\dataserv-client\ and start the gui again. It will download the new dataserv-client version.

**Comment by gordonwritescode** [comment]
The `Updater` only checks for new DriveShare versions, which is why you were not notified. I will think about the best way to check `dataserv-client` updates as well.

**Comment by littleskunk** [comment]
Retest passed. I downloaded the old version 0.4.1 and installed dataserv-client 2.1.4 myself. New driveshare-gui version downloads the latest dataserv-client version.

Fix will come with driveshare-gui 0.4.2.
